version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    network_mode: "host"
  momgodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: iot
    network_mode: "host"
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: "host"
  fast-api:
    image: bhuvanesh452/open-source-docker:mqtt-fast-api-v1
#    if we need to use image from local please comment the above one and use the image name what we have given at the time of running sudo docker build -t <image_name:tag>
#    image: mqtt-fast-api:latest
    ports:
      - "8000:8000"
    network_mode: "host"

  mqtt-publisher:
    image: bhuvanesh452/open-source-docker:mqtt-publisher-v1
#    if we need to use image from local please comment the above one and use the image name what we have given at the time of running sudo docker build -t <image_name:tag>
#    image: mqtt-publisher:latest
    depends_on:
      - mosquitto
    network_mode: "host"
    environment:
      redish_host: 0.0.0.0
      mongo_host: 0.0.0.0
      mqtt_broker_address: 0.0.0.0

  mqtt-receiver:
    image: bhuvanesh452/open-source-docker:mqtt-receiver-v1
#    if we need to use image from local please comment the above one and use the image name what we have given at the time of running sudo docker build -t <image_name:tag>
#    image: mqtt-receiver:latest
    depends_on:
      - mosquitto
      - mqtt-publisher
    network_mode: "host"
    environment:
      redish_host: 0.0.0.0
      mongo_host: 0.0.0.0
      mqtt_broker_address: 0.0.0.0


