version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    network_mode: "host"
  momgodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: iot
    network_mode: "host"
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: "host"
  fast-api:
    image: mqtt-fast-api:latest
    ports:
      - "8000:8000"
    network_mode: "host"

  mqtt-publisher:
    image: mqtt-publisher:latest
    depends_on:
      - mosquitto
    network_mode: "host"

  mqtt-receiver:
    image: mqtt-receiver:latest
    depends_on:
      - mosquitto
      - mqtt-publisher
    network_mode: "host"



